name = "Hero"
license = "MIT"
licenselink = "https://github.com/zerostaticthemes/hugo-hero-theme/blob/master/LICENSE"
description = "El proposito de ADN es ayudar a las pequeñas y medianas organizaciones a aprovechar su máximo potencial, brindamos servicios en SQL Server, apoyo DBA part-time y  consultorias en ETL e integraciones."

homepage = "https://github.com/zerostaticthemes/hugo-hero-theme"
demosite = "https://hugo-hero.netlify.app/"

tags = ["responsive","minimal","clean","company","portfolio","bootstrap","zerostatic"]
features = ["services","work","fullwidth","hero images"]

[author]
  name = "Felipe Schneider"
  homepage = "https://www.linkedin.com/company/adnuy"
