baseURL = "https://www.example.com/"
languageCode = "en-us"
title = "Hugo Hero Theme"
themesDir = "../.."
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo-mobile.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo.svg"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "Hugo Hero"

  [params.homepage_meta_tags]
    meta_description = "El proposito de ADN es ayudar a las peque침as y medianas organizaciones a aprovechar su m치ximo potencial, brindamos servicios en SQL Server, apoyo DBA part-time y  consultorias en ETL e integraciones"
    meta_og_title = "Hugo Hero Theme"
    meta_og_type = "website"
    meta_og_url = "https://hugo-hero.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "El proposito de ADN es ayudar a las peque침as y medianas organizaciones a aprovechar su m치ximo potencial, brindamos servicios en SQL Server, apoyo DBA part-time y  consultorias en ETL e integraciones"
    meta_twitter_card = "summary"
    meta_twitter_site = "@felipes88"
    meta_twitter_creator = "@felipes88"

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "History"
    url = "/history/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
